#!/bin/bash

# Terraform Infrastructure Summary
# This shows what will be created when you run the Jenkins build

echo "========================================="
echo "TERRAFORM INFRASTRUCTURE PLAN"
echo "========================================="
echo ""

echo "✅ VPC Configuration:"
echo "   - CIDR Block: 10.0.0.0/16"
echo "   - DNS Hostnames: Enabled"
echo "   - DNS Support: Enabled"
echo "   - Name: expense-tracker-vpc"
echo ""

echo "✅ Networking Components:"
echo "   - Internet Gateway: expense-tracker-igw"
echo "   - Public Subnet: 10.0.1.0/24 (us-east-1a)"
echo "   - Route Table: expense-tracker-public-rt"
echo "   - Route: 0.0.0.0/0 → Internet Gateway"
echo ""

echo "✅ Security Group (expense-tracker-ec2-sg):"
echo "   Inbound Rules:"
echo "   - Port 22 (SSH): 0.0.0.0/0"
echo "   - Port 3000 (React Frontend): 0.0.0.0/0"
echo "   - Port 4000 (Node.js Backend): 0.0.0.0/0"
echo "   - Port 27017 (MongoDB): 10.0.0.0/16 (VPC only)"
echo "   Outbound Rules:"
echo "   - All traffic: 0.0.0.0/0"
echo ""

echo "✅ EC2 Instance:"
echo "   - AMI: ami-0c7217cdde317cfec (Ubuntu 22.04 LTS)"
echo "   - Instance Type: t3.micro"
echo "   - SSH Key: expense-tracker-key"
echo "   - Name: expense-tracker-server"
echo "   - Root Volume: 20GB gp3"
echo "   - User Data: Installs python3 and python3-pip"
echo ""

echo "✅ Elastic IP:"
echo "   - Will be assigned to the EC2 instance"
echo "   - Name: expense-tracker-eip"
echo ""

echo "✅ Resource Creation Order:"
echo "   1. VPC"
echo "   2. Internet Gateway (attached to VPC)"
echo "   3. Public Subnet (in VPC)"
echo "   4. Security Group (in VPC)"
echo "   5. Route Table (with internet route)"
echo "   6. Route Table Association (subnet ↔ route table)"
echo "   7. EC2 Instance (waits for IGW and route table)"
echo "   8. Elastic IP (attached to EC2, waits for IGW)"
echo "   9. Ansible Inventory (auto-generated with public IP)"
echo ""

echo "✅ Outputs (will be displayed after creation):"
echo "   - Instance ID"
echo "   - Public IP Address"
echo "   - Public DNS Name"
echo "   - SSH Command"
echo "   - Frontend URL (http://IP:3000)"
echo "   - Backend URL (http://IP:4000)"
echo "   - Ansible Inventory"
echo ""

echo "========================================="
echo "IMPORTANT NOTES"
echo "========================================="
echo ""
echo "⚠️  Before running Jenkins build, ensure:"
echo "   1. All old EC2 instances are terminated ✓ (you already did this)"
echo "   2. SSH key 'expense-tracker-key' exists in AWS us-east-1"
echo "   3. Jenkins has AWS credentials configured"
echo "   4. Jenkins has Docker Hub credentials configured"
echo ""

echo "🚀 To run the deployment:"
echo "   1. Go to Jenkins"
echo "   2. Click 'Build Now' on your pipeline"
echo "   3. Watch the console output"
echo ""

echo "⏱️  Expected build time: 8-12 minutes"
echo "   - Docker builds: ~2 min (cached)"
echo "   - Terraform apply: ~3 min (VPC + EC2)"
echo "   - Wait for EC2: ~2 min (SSH availability)"
echo "   - Ansible configure: ~3 min (Docker installation)"
echo "   - Ansible deploy: ~2 min (container startup)"
echo ""

echo "✅ All infrastructure will be created fresh in the correct VPC!"
echo "✅ SSH access will work properly this time!"
echo ""
