# Terraform Variables Configuration File

# AWS Configuration
aws_region = "us-east-1"

# EC2 Instance Configuration
# AMI ID for Ubuntu 22.04 LTS in us-east-1
ami_id = "ami-0c7217cdde317cfec"

# Instance type
instance_type = "t3.micro"

# SSH Key Pair (auto-generated by Terraform)
key_name = "expense-tracker-key"

# Environment
environment = "production"

# Project Name
project_name = "expense-tracker"
